### ISSUE TITLE
Trabajo del estilo de la web.

### ISSUE THREAD

**Issue by JMailloH** [babeltowerteam/cloudsarao#36]
@eleion referencia a este issue el trabajo de estilo.

Comentarte para que no se olvide modificar el tamaño del html insertar_sarao.html del campo hora (son dos campos numéricos limitados en máximo y mínimo).

:+1:

**Comment by eleion** [comment]
¡Vale! Lo anoto. :smile:

**Comment by eleion** [comment]
Comienzo ahora a trabajar con el formulario **insertar sarao**.

**Comment by eleion** [comment]
Se me ha olvidado poner en el último commit que he modificado cosas de 'modificar sarao'.

**Comment by JMailloH** [comment]
Luis te encargas tu de nuevo de bootstrap. Me pongo con @Crixo24 y @alvaromm sobre python.

**Comment by eleion** [comment]
Se ha producido un conflicto en mis ficheros en **modificar_sarao.html**. ¡Tengo que modificarlo de nuevo! :sob:

**Comment by alvaromm** [comment]
Ahora mismo todo funciona correctamente, así que actualizaros desde el **master** y continuad trabajando desde ahí.

**Comment by eleion** [comment]
Yo creo que este ISSUE ha sido más que explotado y trabajado. 
Se puede dar por confluida la labor de estilo.
