### ISSUE TITLE
[Problema] Bucle de redireccionamiento

### ISSUE THREAD

**Issue by potray** [babeltowerteam/cloudsarao#38]
Al dar permisos sobre la cuenta de Google te lleva a un sitio con un bucle de redireccionamiento.

De hecho la página de administración es la que tiene un bucle de redireccionamiento: al acceder a ella de nuevo desde el icono del engranaje en cloud-sarao.appspot.com vuelve a salir.

**Comment by alvaromm** [comment]
Eso es porque no tienes permisos de administración. Esa funcionalidad no está todavía implementada.
Gracias por tu colaboración.

El equipo de BTT.

**Comment by eleion** [comment]
Este problema se solucionó ya.
