### ISSUE TITLE
[Mejora] Cambiar de página cuando te metes en un sarao

### ISSUE THREAD

**Issue by potray** [babeltowerteam/cloudsarao#39]
Cuando te apuntas a un sarao te lleva a una página con texto plano que te dice "Añadido asistente". Sería bueno que te redireccionara a la página del sarao o a la página principal y que ese mensaje te saliera como un __alert__ de Javascript o algo parecido, ya que desde ahí no puedes hacer nada.

**Comment by JMailloH** [comment]
Gracias Dani, sabemos que no está terminada y aún le quedan cositas por refinar. También hay enlaces mál puestos y funcionalidad que ya está lista para añadirse pero no está "linckada" desde la web.

**Comment by alvaromm** [comment]
Exacto, la idea es que te redireccione a la página de visualización de saraos. Gracias @potray por tu interés y ayuda. 
Seguimos trabajando.

**Comment by alvaromm** [comment]
Hay un bug en **webapp2** de Python y la función `request.redirect()` sólo redirecciona, pero no refresca la página. ¿Alguna idea o "apaño" con JS?

**Comment by eleion** [comment]
Hay que hacer un parche bastante cutre para arreglarlo. Realmente no es problema nuestro, sino de la librería. La solución es **refrescar la página.**
