### ISSUE TITLE
Página administración lugares

### ISSUE THREAD

**Issue by alvaromm** [babeltowerteam/cloudsarao#46]
Falta la página de adminstración de lugares. La lógica la haremos @Crixo24 y yo, pero necesitamos las plantillas HTML (se pueden hacer casi igual que la de los saraos).

**Comment by eleion** [comment]
Yo me encargo de hacer el HTML.

**Comment by eleion** [comment]
Aunque ya tenemos un **gestionar_lugares.html** ¿eso es lo que querías? ¿o es otra cosa?

**Comment by alvaromm** [comment]
Es lo que quería, pero hay que hacer la conexión con el sistema y que reenderice los lugares disponibles.

**Comment by JMailloH** [comment]
En principio los html los hicimos todos entre @sergiogvz  y yo, a falta de los botones y poner en comun los campos de jinja2 con los de las clases python, que no pudimos hacerlo porque aún no estaba terminada la parte de python.

**Comment by alvaromm** [comment]
De acuerdo, pues este viernes lo terminamos.
