### ISSUE TITLE
Menu bootstrap a la derecha

### ISSUE THREAD

**Issue by alvaromm** [babeltowerteam/cloudsarao#49]
Pienso que el menu desplegable de Bootstrap para dispositivos móviles debería tener el texto (o la imagen del engranaje) justificado a la derecha. Creo recordar que habia que usar "push-right" o algo así.

**Comment by alvaromm** [comment]
Asignado a @eleion

**Comment by Crixo24** [comment]
A mi me parece bien, porque es más usable ;)

**Comment by alvaromm** [comment]
Nielsen approves this conversation.

**Comment by eleion** [comment]
Este ISSUE ya no tienen sentido, ¿no? 
Puesto que hemos puesto el menú directamente y no se despliega.

**Comment by alvaromm** [comment]
No, cuando se visualiza la web en dispositivos móviles sigue desplegándose.

**Comment by alvaromm** [comment]
Prueba a reducir horizontalmente la ventana del navegador.

**Comment by eleion** [comment]
Ok. Pues ya tengo la solución.
En cuanto me ponga modifico la barra. :smile:
