### ISSUE TITLE
Modificar Sarao

### ISSUE THREAD

**Issue by Crixo24** [babeltowerteam/cloudsarao#50]
A ver, alguien ha estado tocando en la parte de "Modificar Sarao" y la ha liado parda. ¿A quién hay que cortarle los deditos? xD

**Comment by eleion** [comment]
Yo modifiqué de nuevo lo que tú me cambiaste cuando no hiciste el pull. Pero yo modifiqué el HTML, no sé si a eso te refieres...

**Comment by eleion** [comment]
Pero ojo, que yo comprobé que se desplegaba bien después de los cambios e iba todo bien... :disappointed:

**Comment by alvaromm** [comment]
Yo estuve tocando muchas cosas, pero no lie parda nada porque no creó conflictos ni nada, simplemente me actualicé, modifiqué y volví a hacer push. Quedaos con mi repo que es el más actualizado y funciona bien.

**Comment by alvaromm** [comment]
Ah sí, sí lo sé. Ha sido @eleion (o eso pone en el log de commits). Por favor, como norma antes de tocar nada haced un git pull <nombre del repo de BTT.git>

**Comment by Crixo24** [comment]
Esto ya lo arregló @alvaromm así que cerrando issue.
